#!/bin/bash
export LOCATION_CASSANDRA_ENDPOINT='127.0.0.1'
time spark-submit --name backupLocations \
                  --class io.rhom.BackupLocations \
                  --packages datastax:spark-cassandra-connector:2.0.7-s_2.11,org.apache.hadoop:hadoop-azure:2.7.2,com.microsoft.azure:azure-storage:3.1.0,com.databricks:spark-avro_2.11:4.0.0 \
                  rhom-backup-locations_2.11-0.1.0-SNAPSHOT.jar 
