#!/bin/bash
export LOCATION_CASSANDRA_ENDPOINT='10.1.0.10'
export HADOOP_CONF_DIR=/opt/spark-2.2.0-bin-hadoop2.7/conf
cp core-site-prod.xml $HADOOP_CONF_DIR/core-site.xml
time spark-submit --master spark://spark-master:7077 
                  --num-executors 6 
                  --executor-cores 16 
                  --executor-memory 89g 
                  --driver-memory 18g 
                  --name backupLocations \
                  --class io.rhom.BackupLocations \
                  --packages datastax:spark-cassandra-connector:2.0.7-s_2.11,org.apache.hadoop:hadoop-azure:2.7.2,com.microsoft.azure:azure-storage:3.1.0,com.databricks:spark-avro_2.11:4.0.0 \
                  rhom-backup-locations_2.11-0.1.0-SNAPSHOT.jar 
