#!/bin/bash
export HADOOP_CONF_DIR=/Users/tpark/dev/rhom/data/backupLocations
cd /Users/tpark/bin/spark-2.3.0-bin-hadoop2.7
spark-submit --conf spark.cassandra.connection.host=127.0.0.1 \
             --name backupLocations \
             --class io.rhom.BackupLocations \
             --jars https://dl.bintray.com/spark-packages/maven/datastax/spark-cassandra-connector/2.0.7-s_2.11/spark-cassandra-connector-2.0.7-s_2.11.jar \
             target/scala-2.11/rhom-backup-locations_2.11-0.1.0-SNAPSHOT.jar
cd /Users/tpark/dev/rhom/data/backupLocationsScala
